### PR TITLE
Fix GoodName missing from Project64.cfg

### LINKED ISSUE #1263: Good Names missing from .cfg.
In 2.3.2-200, .cfg has Good Names.  But Good Names are disappearing in .cfg with 2.3.2-202, if I Edit game settings.  Good Name is no longer written at all to .cfg.

Guessing it's caused by https://github.com/project64/project64/commit/bf0ba50dc494f21b91a353c3ab9a926a5699d0d8.

### PR DESCRIPTION
**Pull request by Frank-74**
Fix #1263.

### CODE REVIEW

File: Source/Project64/UserInterface/SettingsConfig.cpp [hunk 1]
```diff
@@ -251,9 +251,9 @@ void CSettingConfig::ApplySettings(bool UpdateScreen)
     if (!GameIni.empty())
     {
         stdstr GoodName;
-        if (!g_Settings->LoadStringVal(Game_GoodName, GoodName))
+        if (!g_Settings->LoadStringVal(Cfg_GoodName, GoodName))
```
Comment (Frank-74) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: Wasn't sure if this should be Rdb_GoodName.

Comment (project64) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: should be 

if (g_Settings->LoadStringVal(Rdb_GoodName, GoodName))

Since Cfg_GoodName does not inherit from Rdb_GoodName it would be always writing an empty string to the cfg file

Comment (project64) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: the way the setting class works is that it will load it from the source, if it does not exist it will read if from the default.

it will return true if read from the source, false if from the default.

So if this returned false before it read it from rdb_goodname so had the goodname now in the variable, and then could just write it.

Looks good, so basically all reads come from rdb_goodname and all writes are to cfg_goodname

Comment (Frank-74) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: Ok, changed it to read from Rdb, write to Cfg.  I should have done what I thought in the first place.

Good to go?

File: Source/Project64/UserInterface/SettingsConfig.cpp [hunk 2]
```diff
@@ -251,7 +251,7 @@ void CSettingConfig::ApplySettings(bool UpdateScreen)
     if (!GameIni.empty())
     {
         stdstr GoodName;
-        if (!g_Settings->LoadStringVal(Cfg_GoodName, GoodName))
+        if (!g_Settings->LoadStringVal(Rdb_GoodName, GoodName))
```
Comment (project64) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: Remove the !

Comment (project64) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: it can be just Load then save do not even need the if statement

Comment (Frank-74) [inline Source/Project64/UserInterface/SettingsConfig.cpp]: Removed the !.
